apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-storybook-conf
  namespace: preprod
data:
  default.conf: |
    server {
        listen 6006;
        server_name _;
        root /var/www;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }